version: "3.9"
services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    depends_on:
      evolution_redis:
        condition: service_healthy
      evolution_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  evolution_postgres:
    image: postgres:15
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: evolution_pass
      POSTGRES_DB: evolution
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
  evolution_redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6378:6379

volumes:
  evolution_redis:
  evolution_instances:
  evolution_postgres_data:
  pgadmin_data:
