services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  worker:
    image: n8nio/n8n:latest
    entrypoint: ["n8n", "worker"]
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  postgres_data:
  redis_data:
  n8n_data:
